package modelo.entidad;
// Generated 23-oct-2021 15:26:17 by Hibernate Tools 4.3.1



/**
 * Registro generated by hbm2java
 */
public class Registro  implements java.io.Serializable {


     private int idalumno;
     private String nombre;
     private String apellido;
     private String correo;
     private String direccion;
     private String edad;
     private String carrera;

    public Registro() {
    }

	
    public Registro(int idalumno) {
        this.idalumno = idalumno;
    }
    public Registro(int idalumno, String nombre, String apellido, String correo, String direccion, String edad, String carrera) {
       this.idalumno = idalumno;
       this.nombre = nombre;
       this.apellido = apellido;
       this.correo = correo;
       this.direccion = direccion;
       this.edad = edad;
       this.carrera = carrera;
    }
   
    public int getIdalumno() {
        return this.idalumno;
    }
    
    public void setIdalumno(int idalumno) {
        this.idalumno = idalumno;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getEdad() {
        return this.edad;
    }
    
    public void setEdad(String edad) {
        this.edad = edad;
    }
    public String getCarrera() {
        return this.carrera;
    }
    
    public void setCarrera(String carrera) {
        this.carrera = carrera;
    }




}


